# Copyright 2020 Energinet DataHub A/S
#
# Licensed under the Apache License, Version 2.0 (the "License2");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Publish Energinet.DataHub.MessageArchive.Client.Abstractions nuget package

on:
  push:
    branches:
      - main
    paths:
      - source/Energinet.DataHub.MessageArchive.Client.Abstractions/**
      - .github/workflows/publish-messagearchive-integration-client.yml
      - .github/actions/publish-nuget-package/**
  pull_request:
    branches:
      - main
    paths:
      - source/Energinet.DataHub.MessageArchive.Client.Abstractions/**
      - .github/workflows/publish-messagearchive-client-abstractions.yml
      - .github/actions/publish-nuget-package/**
  workflow_dispatch: {}

env:
  DOTNET_VERSION: '6.0.201'
  CSPROJ_FILE_PATH: 'source/Energinet.DataHub.MessageArchive.Client.Abstractions/Energinet.DataHub.MessageArchive.Client.Abstractions.csproj'
  BINARY_PATH: 'source/Energinet.DataHub.MessageArchive.Client.Abstractions/bin/Release/*.nupkg'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    name: Publish to nuget feed
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Pack and publish nuget package
        uses: ./.github/actions/publish-nuget-package
        with:
          dotnet_version: ${{ env.DOTNET_VERSION }}
          csproj_file_path: ${{ env.CSPROJ_FILE_PATH }}
          binary_path: ${{ env.BINARY_PATH }}
          nuget_token: ${{ secrets.NUGET_TOKEN }}
